// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAaNdHOmvdFqSbskgD9PF575smo0mYSCE',
    appId: '1:816993708998:web:28bc523c1136a7ef15a0c7',
    messagingSenderId: '816993708998',
    projectId: 'sigesproc-7mageneracion',
    authDomain: 'sigesproc-7mageneracion.firebaseapp.com',
    storageBucket: 'sigesproc-7mageneracion.appspot.com',
    measurementId: 'G-BXHLQ2P9XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOiZCVZgs7nw1PHRUFhEMm995sK4nlsD4',
    appId: '1:816993708998:android:7e4b079cfcaeb2b415a0c7',
    messagingSenderId: '816993708998',
    projectId: 'sigesproc-7mageneracion',
    storageBucket: 'sigesproc-7mageneracion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDQVD9bhJkREydLmA-ZhHhkCwlcyvAgag',
    appId: '1:816993708998:ios:8035425c87a800a515a0c7',
    messagingSenderId: '816993708998',
    projectId: 'sigesproc-7mageneracion',
    storageBucket: 'sigesproc-7mageneracion.appspot.com',
    iosBundleId: 'com.sigesproc.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAaNdHOmvdFqSbskgD9PF575smo0mYSCE',
    appId: '1:816993708998:web:f57ebd5d3cce14a715a0c7',
    messagingSenderId: '816993708998',
    projectId: 'sigesproc-7mageneracion',
    authDomain: 'sigesproc-7mageneracion.firebaseapp.com',
    storageBucket: 'sigesproc-7mageneracion.appspot.com',
    measurementId: 'G-YRQFQ41H94',
  );
}
